//////////////////////////////////////////////////////////////////////////
//
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//
//////////////////////////////////////////////////////////////////////////

#ifndef UNITY_TERRAIN_TOOL_NOISE_NoneValue_INC
#define UNITY_TERRAIN_TOOL_NOISE_NoneValue_INC

/*=========================================================================

    Includes

=========================================================================*/

#include "Assets/Procedural Worlds/Gaia/Shaders/Unity/Terrain Tools/NoiseLib/Implementation/ValueImpl.hlsl"
#include "Assets/Procedural Worlds/Gaia/Shaders/Unity/Terrain Tools/NoiseLib/NoiseCommon.hlsl"



/*=========================================================================
    
    NoneValue Noise Functions - Non-Fractal, Non-Warped

=========================================================================*/

float noise_NoneValue( float pos )
{
    return get_noise_Value( pos );
}

float noise_NoneValue( float2 pos )
{
    return get_noise_Value( pos );
}

float noise_NoneValue( float3 pos )
{
    return get_noise_Value( pos );
}

float noise_NoneValue( float4 pos )
{
    return get_noise_Value( pos );
}

#endif // UNITY_TERRAIN_TOOL_NOISE_NoneValue_INC